name: events
version: 0.1.1+1
author: Steven Roose <stevenroose@gmail.com>
description: A library for event handling in Dart.
homepage: https://github.com/stevenroose/dart-events
dependencies:
  stevenroose: ">= 0.1.0"
dev_dependencies:
  browser: any
  unittest: any
  streamers:
    git: https://github.com/0xor1/streamers